// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sample_B
arma::vec sample_B(const arma::mat& Lambda, const arma::mat& Sigma_tilde, const arma::mat& Phi_X, const arma::mat& A, const arma::vec& y, int p, int q, int m);
RcppExport SEXP _BayesVFLReg_sample_B(SEXP LambdaSEXP, SEXP Sigma_tildeSEXP, SEXP Phi_XSEXP, SEXP ASEXP, SEXP ySEXP, SEXP pSEXP, SEXP qSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_tilde(Sigma_tildeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Phi_X(Phi_XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_B(Lambda, Sigma_tilde, Phi_X, A, y, p, q, m));
    return rcpp_result_gen;
END_RCPP
}
// sample_A
arma::vec sample_A(const arma::mat& Sigma_tilde, const arma::mat& Phi_X, const arma::mat& B, const arma::vec& y, int q);
RcppExport SEXP _BayesVFLReg_sample_A(SEXP Sigma_tildeSEXP, SEXP Phi_XSEXP, SEXP BSEXP, SEXP ySEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_tilde(Sigma_tildeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Phi_X(Phi_XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_A(Sigma_tilde, Phi_X, B, y, q));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesVFLReg_sample_B", (DL_FUNC) &_BayesVFLReg_sample_B, 8},
    {"_BayesVFLReg_sample_A", (DL_FUNC) &_BayesVFLReg_sample_A, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesVFLReg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
