# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_B <- function(Lambda, Sigma_tilde, Phi_X, A, y, p, q, m) {
    .Call('_BayesVFLReg_sample_B', PACKAGE = 'BayesVFLReg', Lambda, Sigma_tilde, Phi_X, A, y, p, q, m)
}

sample_A <- function(Sigma_tilde, Phi_X, B, y, q) {
    .Call('_BayesVFLReg_sample_A', PACKAGE = 'BayesVFLReg', Sigma_tilde, Phi_X, B, y, q)
}

